# Generated by Django 5.2.9 on 2025-12-21 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_currentlisting"),
        ("rankings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RankingComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "winner",
                    models.CharField(
                        choices=[
                            ("A", "Listing A"),
                            ("B", "Listing B"),
                            ("TIE", "Tie"),
                        ],
                        max_length=3,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "listing_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_as_a",
                        to="listings.mlshistory",
                    ),
                ),
                (
                    "listing_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_as_b",
                        to="listings.mlshistory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ranking Comparisons",
            },
        ),
        migrations.CreateModel(
            name="RankingScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=1000.0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranking_scores",
                        to="listings.mlshistory",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserComparisonFeedback",
        ),
        migrations.DeleteModel(
            name="UserPreferenceConfig",
        ),
        migrations.DeleteModel(
            name="UserRankingScore",
        ),
    ]
