# Generated by Django 5.2.9 on 2025-12-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rankings", "0002_rankingcomparison_rankingscore_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FeatureWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_name", models.CharField(max_length=50, unique=True)),
                ("weight", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="LearnedPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("value", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="NeighborhoodWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("neighborhood_name", models.CharField(max_length=255, unique=True)),
                ("weight", models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name="rankingscore",
            name="score",
            field=models.FloatField(default=0.0),
        ),
    ]
