# Generated by Django 5.2.9 on 2025-12-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rankings", "0003_favoritelocation_featureweight_learnedpreference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rankingcomparison",
            name="winner",
            field=models.CharField(
                choices=[
                    ("A", "Listing A"),
                    ("B", "Listing B"),
                    ("TIE", "Tie"),
                    ("NEITHER", "Neither"),
                ],
                max_length=7,
            ),
        ),
    ]
