# Generated by Django 5.2.9 on 2025-12-11 17:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MlsHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scrape_timestamp", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("property_url", models.TextField(blank=True, null=True)),
                (
                    "property_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("listing_id", models.CharField(blank=True, max_length=100, null=True)),
                ("permalink", models.TextField(blank=True, null=True)),
                ("mls", models.CharField(blank=True, max_length=100, null=True)),
                ("mls_id", models.CharField(blank=True, max_length=100, null=True)),
                ("mls_status", models.CharField(blank=True, max_length=50, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("style", models.CharField(blank=True, max_length=100, null=True)),
                ("formatted_address", models.TextField(blank=True, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "full_street_line",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=20, null=True)),
                ("neighborhoods", models.TextField(blank=True, null=True)),
                ("county", models.CharField(blank=True, max_length=100, null=True)),
                ("fips_code", models.CharField(blank=True, max_length=20, null=True)),
                ("beds", models.FloatField(blank=True, null=True)),
                ("full_baths", models.FloatField(blank=True, null=True)),
                ("half_baths", models.FloatField(blank=True, null=True)),
                ("sqft", models.FloatField(blank=True, null=True)),
                ("year_built", models.IntegerField(blank=True, null=True)),
                ("days_on_mls", models.IntegerField(blank=True, null=True)),
                ("stories", models.IntegerField(blank=True, null=True)),
                ("new_construction", models.BooleanField(blank=True, null=True)),
                ("lot_sqft", models.FloatField(blank=True, null=True)),
                ("primary_photo", models.TextField(blank=True, null=True)),
                ("alt_photos", models.TextField(blank=True, null=True)),
                (
                    "list_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "list_price_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "list_price_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("list_date", models.DateField(blank=True, null=True)),
                ("pending_date", models.DateField(blank=True, null=True)),
                (
                    "sold_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("last_sold_date", models.DateField(blank=True, null=True)),
                (
                    "last_sold_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "assessed_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("tax_history", models.TextField(blank=True, null=True)),
                (
                    "price_per_sqft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "hoa_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("agent_id", models.CharField(blank=True, max_length=100, null=True)),
                ("agent_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "agent_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("agent_phones", models.TextField(blank=True, null=True)),
                ("agent_mls_set", models.TextField(blank=True, null=True)),
                (
                    "agent_nrds_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("broker_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "broker_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("builder_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "builder_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("office_id", models.CharField(blank=True, max_length=100, null=True)),
                ("office_mls_set", models.TextField(blank=True, null=True)),
                (
                    "office_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "office_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("office_phones", models.TextField(blank=True, null=True)),
                ("nearby_schools", models.TextField(blank=True, null=True)),
                ("parking_garage", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
