# Generated by Django 5.2.9 on 2025-12-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = []
